require "weixin_authorize/api/user"
require "weixin_authorize/api/menu"
require "weixin_authorize/api/custom"
require "weixin_authorize/api/groups"
require "weixin_authorize/api/qrcode"
require "weixin_authorize/api/media"
require "weixin_authorize/api/oauth"
require "weixin_authorize/api/template"
